// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "errors"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type PeerName struct {
	// The peer's name
	Value string `json:"value" yaml:"value" mapstructure:"value"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *PeerName) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in PeerName: required")
	}
	type Plain PeerName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = PeerName(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *PeerName) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	if _, ok := raw["value"]; raw != nil && !ok {
		return fmt.Errorf("field value in PeerName: required")
	}
	type Plain PeerName
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = PeerName(plain)
	return nil
}

type AnyOfNullExpectedPeerName_0 = PeerName

type AnyOfNull struct {
	// ExpectedPeerName corresponds to the JSON schema field "expected_peer_name".
	ExpectedPeerName *AnyOfNullExpectedPeerName `json:"expected_peer_name,omitempty" yaml:"expected_peer_name,omitempty" mapstructure:"expected_peer_name,omitempty"`
}

type AnyOfNullExpectedPeerName struct {
	// The peer's name
	Value *string `json:"value,omitempty" yaml:"value,omitempty" mapstructure:"value,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOfNullExpectedPeerName) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOfNullExpectedPeerName_0 AnyOfNullExpectedPeerName_0
	var errs []error
	if err := json.Unmarshal(value, &anyOfNullExpectedPeerName_0); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOfNullExpectedPeerName
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AnyOfNullExpectedPeerName(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOfNullExpectedPeerName) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var anyOfNullExpectedPeerName_0 AnyOfNullExpectedPeerName_0
	var errs []error
	if err := value.Decode(&anyOfNullExpectedPeerName_0); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 1 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOfNullExpectedPeerName
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOfNullExpectedPeerName(plain)
	return nil
}
