// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

import "encoding/json"
import "errors"
import "fmt"
import yaml "gopkg.in/yaml.v3"

type AnyOf7 struct {
	// Permission corresponds to the JSON schema field "permission".
	Permission *Permission `json:"permission,omitempty" yaml:"permission,omitempty" mapstructure:"permission,omitempty"`

	// Prohibition corresponds to the JSON schema field "prohibition".
	Prohibition *Prohibition `json:"prohibition,omitempty" yaml:"prohibition,omitempty" mapstructure:"prohibition,omitempty"`
}

type AnyOf7_0 struct {
	// Permission corresponds to the JSON schema field "permission".
	Permission *Permission `json:"permission,omitempty" yaml:"permission,omitempty" mapstructure:"permission,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7_0) UnmarshalJSON(value []byte) error {
	type Plain AnyOf7_0
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AnyOf7_0(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf7_0) UnmarshalYAML(value *yaml.Node) error {
	type Plain AnyOf7_0
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf7_0(plain)
	return nil
}

type AnyOf7_1 struct {
	// Prohibition corresponds to the JSON schema field "prohibition".
	Prohibition *Prohibition `json:"prohibition,omitempty" yaml:"prohibition,omitempty" mapstructure:"prohibition,omitempty"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7_1) UnmarshalJSON(value []byte) error {
	type Plain AnyOf7_1
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AnyOf7_1(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf7_1) UnmarshalYAML(value *yaml.Node) error {
	type Plain AnyOf7_1
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf7_1(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *AnyOf7) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	var anyOf7_0 AnyOf7_0
	var anyOf7_1 AnyOf7_1
	var errs []error
	if err := anyOf7_0.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf7_1.UnmarshalJSON(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 2 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOf7
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	*j = AnyOf7(plain)
	return nil
}

// UnmarshalYAML implements yaml.Unmarshaler.
func (j *AnyOf7) UnmarshalYAML(value *yaml.Node) error {
	var raw map[string]interface{}
	if err := value.Decode(&raw); err != nil {
		return err
	}
	var anyOf7_0 AnyOf7_0
	var anyOf7_1 AnyOf7_1
	var errs []error
	if err := anyOf7_0.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if err := anyOf7_1.UnmarshalYAML(value); err != nil {
		errs = append(errs, err)
	}
	if len(errs) == 2 {
		return fmt.Errorf("all validators failed: %s", errors.Join(errs...))
	}
	type Plain AnyOf7
	var plain Plain
	if err := value.Decode(&plain); err != nil {
		return err
	}
	*j = AnyOf7(plain)
	return nil
}

type Permission string

type Prohibition string
