// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package test

type Thing struct {
	// Values corresponds to the JSON schema field "values".
	Values []Value `json:"values,omitempty" yaml:"values,omitempty" mapstructure:"values,omitempty"`
}

type Value float64

type AllOf = Thing

type ExternalRef = Thing
